Cho phép thay đổi cách đọc phần thập phân
phpviet/number-to-words pull request #8
Opened 2021-09-09 09:02 UTC by nhamtphat

Vấn đề này xảy ra khi hiển thị một một số loại tiền tệ có quy đổi mệnh giá như 1 USD = 100 cent thì phần đọc thập phân cũng được thay đổi theo. Ví dụ số $56.90 sẽ đọc là "năm mươi sáu đô chín **mươi** xen" thay vì "năm mươi sáu đô chín ~~mươi~~ xen"

2021-10-14 07:23 UTC, nhamtphat commented
@vuongxuongminh khi nào anh có thời gian review giúp em nhé! Cảm ơn anh

2021-10-15 16:25 UTC, vuongxuongminh requested changes
Cảm ơn @nhamtphat PR chi tiết và đầy đủ, mình có góp ý sau:

+ Decimal part nên là logic cố định của Transformer (được access duy nhất 1 lần thông qua constructor).
+ Mặc định decimal part sẽ là `null` thay vì `-1` (để phân biệt được có giá trị được chỉ định hoặc không có NULL, tính dữ liệu sẽ rõ ràng hơn).
+ Sử dụng `camelCase` cho property name.

2021-10-16 08:48 UTC, vuongxuongminh requested changes

2021-10-16 08:48 UTC, vuongxuongminh commented on src/Concerns/NumberResolver.php
> +    protected function resolveNumber($number, $decimalPart = null): array
`$decimalPart` đã là 1 phần của Transformer nên chúng ta không cần đặt arg tại đây, thay vào đó hãy sử dụng property.

2021-10-16 09:01 UTC, nhamtphat commented
Cảm ơn anh, em đã cập nhật!

2021-10-16 11:09 UTC, vuongxuongminh requested changes

2021-10-16 11:09 UTC, vuongxuongminh commented on tests/CurrencyTest.php
> +    public function testUSDSetDecimalPart($expect, $float, $decimal_part)
`$decimal_part` nên là `$decimalPart`

2021-10-16 11:17 UTC, vuongxuongminh commented
@nhamtphat bạn cần cập nhật CHANGELOG nữa nha.

2021-10-16 14:35 UTC, vuongxuongminh approved these changes

2021-10-16 14:36 UTC, vuongxuongminh commented
Cảm ơn bạn @nhamtphat

2021-10-16 14:36 UTC, merged